### ISSUE TITLE
Add functionality

### ISSUE THREAD

**Issue by davidleach724** [davidleach724/IssuesClassWork#1]
This app does nothing. You gotta add some code is you wanna make that dough'd. 

As a user, when I click on the super idea$ section, I want to be able to view all of the brilliant idea$, so that I can pick one and begin working on it. 

Checkout __________'s site for an example of layout.

**Comment by davidleach724** [comment]
![826D3722-6133-4D0C-8E0D-174906C07BEE_1_105_c](https://user-images.githubusercontent.com/81774070/125319475-0646c480-e2f8-11eb-9e5f-c6ada0180706.jpeg)

**Comment by sarahrudy** [comment]
What kind of idea$ are we talking about here???

**Comment by davidleach724** [comment]
Nice try @sarahrudy, that is sensitive information.
